apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: metallb-calico
spec:
  peerIP: 127.0.0.1
  asNumber: 64513
  nodeSelector: all()

--- 

apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: calico-lb-ippool
spec:
  cidr: 198.51.100.0/24
  disabled: true
