apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    # MetalLB must be in a different AS in order for Calico node BIRD to advertise its IP routes 
    - my-asn: 64513
      peer-asn: 64512
      peer-address: 127.0.0.1
    address-pools:
    - name: my-ip-space
      protocol: bgp
      avoid-buggy-ips: true
      addresses:
      - 198.51.100.0/24